export const YAKU_LIB: YakuDetails[] = [
  {
    name: "gokou",
    points: 15,
    description: ["Five Brights"],
    cards: [
      "matsu-ni-tsuru",
      "sakura-ni-maku",
      "susuki-ni-tsuki",
      "kiri-ni-ho-oh",
      "yanagi-ni-ono-no-toufuu",
    ],
  },
  {
    name: "shikou",
    points: 8,
    description: ["Four Brights"],
    cards: [
      "matsu-ni-tsuru",
      "sakura-ni-maku",
      "susuki-ni-tsuki",
      "kiri-ni-ho-oh",
    ],
  },
  {
    name: "ame-shikou",
    points: 7,
    description: ["Rainy Four Brights ( Any 3 + Rain Man )"],
    cards: [
      "matsu-ni-tsuru",
      "sakura-ni-maku",
      "susuki-ni-tsuki",
      "kiri-ni-ho-oh",
      "yanagi-ni-ono-no-toufuu",
    ],
  },
  {
    name: "sankou",
    description: ["Three Brights ( Any 3 )"],
    points: 6,
    cards: [
      "matsu-ni-tsuru",
      "sakura-ni-maku",
      "susuki-ni-tsuki",
      "kiri-ni-ho-oh",
    ],
  },
  {
    name: "ino-shika-chou",
    points: 5,
    description: ["Boar, Deer & Butterfly"],
    cards: ["hagi-ni-inoshishi", "momiji-ni-shika", "botan-ni-chou"],
  },
  {
    name: "hanami-zake",
    points: 5,
    description: ["Flower Viewing"],
    cards: ["sakura-ni-maku", "kiku-ni-sakazuki"],
  },
  {
    name: "tsukimi-zake",
    points: 5,
    description: ["Moon Viewing"],
    cards: ["susuki-ni-tsuki", "kiku-ni-sakazuki"],
  },
  {
    name: "aka-tan",
    points: 5,
    description: ["Red Poetry Ribbons"],
    cards: ["matsu-no-tan", "ume-no-tan", "sakura-no-tan"],
  },
  {
    name: "ao-tan",
    points: 5,
    description: ["Blue Ribbons"],
    cards: ["botan-no-tan", "kiku-no-tan", "momiji-no-tan"],
  },
  {
    name: "tan-zaku",
    points: 1,
    description: ["Any 5 Ribbons ( +1pt for each extra )"],
    cards: CARDS.filter(isRibbon),
  },
  {
    name: "tane-zaku",
    points: 1,
    description: ["Any 5 Animals ( +1pt for each extra )"],
    cards: CARDS.filter(isAnimal),
  },
  {
    name: "kasu",
    points: 1,
    description: ["Any 10 Plains ( +1pt for each extra )"],
    cards: CARDS.filter(isPlain),
  },
];
